"""Render complete, defaulted, commented non-secret env files per deploy target.

Single source of truth = the `GatewaySettings` schema (`settings.py`) + the
declarative `config_spec`. `render_target()` produces the text written to
`deploy/config/gateway.<target>.env`. See the ADR
`engineering/decisions/2026-08-05-gateway-config-generation.md`.
"""
from __future__ import annotations

from pathlib import Path

from pydantic_core import PydanticUndefined

from . import config_spec as spec
from .settings import AuthSettings, GatewaySettings


def env_name(key: str) -> str:
    """Field key → the env var name GatewaySettings reads it from."""
    if key.startswith("auth."):
        return "GATEWAY_AUTH__" + key[len("auth."):].upper()
    field = GatewaySettings.model_fields[key]
    alias = field.validation_alias
    if isinstance(alias, str):
        return alias
    return "GATEWAY_" + key.upper()


def _schema_default(key: str) -> object:
    if key.startswith("auth."):
        field = AuthSettings.model_fields[key[len("auth."):]]
    else:
        field = GatewaySettings.model_fields[key]
    if field.default is not PydanticUndefined:
        return field.default
    return None


def effective_value(target: str, key: str) -> object:
    """Schema default ⊕ COMMON ⊕ PROFILES[target]."""
    val = _schema_default(key)
    if key in spec.COMMON:
        val = spec.COMMON[key]
    if key in spec.PROFILES.get(target, {}):
        val = spec.PROFILES[target][key]
    return val


def fmt(val: object) -> str:
    if val is None:
        return ""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, Path):
        return str(val)
    return str(val)


def all_field_keys() -> set[str]:
    top = set(GatewaySettings.model_fields)
    nested = {f"auth.{k}" for k in AuthSettings.model_fields}
    return top | nested


def surfaced_keys() -> list[str]:
    return [k for _title, keys in spec.SECTIONS for k in keys]


def _wrap_comment(text: str, width: int = 88) -> list[str]:
    """Word-wrap a doc string into `# ` comment lines."""
    words = text.split()
    lines: list[str] = []
    cur = "#"
    for w in words:
        if len(cur) + 1 + len(w) > width and cur != "#":
            lines.append(cur)
            cur = "# " + w
        else:
            cur = f"{cur} {w}"
    if cur != "#":
        lines.append(cur)
    return lines


def render_target(target: str) -> str:
    if target not in spec.TARGETS:
        raise ValueError(f"unknown target {target!r}; expected one of {spec.TARGETS}")
    secret_file = spec.SECRET_FILE[target]
    out: list[str] = [
        f"# gateway {target} — COMPLETE non-secret config (generated by `make gen-config`).",
        "# Every operator-relevant GATEWAY_* knob is listed with its default. Edit",
        "# values in place (e.g. GATEWAY_OSS_BUCKET), then run `make check-config`.",
        f"# Secrets are commented placeholders — set them in deploy/{target}/{secret_file}.",
        "# DO NOT hand-edit structure: regenerate with `make gen-config`.",
    ]
    for title, keys in spec.SECTIONS:
        out.append("")
        out.append(f"# === {title} ===")
        for key in keys:
            out.extend(_render_field(target, key, secret_file))
    externals = spec.EXTERNAL_SECRETS.get(target, [])
    if externals:
        out.append("")
        out.append("# === Secrets (external; set in the target's env file) ===")
        for name in externals:
            out.append(f"# {name}=   # SECRET — set in deploy/{target}/{secret_file}")
    return "\n".join(out) + "\n"


def _render_field(target: str, key: str, secret_file: str) -> list[str]:
    lines: list[str] = []
    doc = spec.DOCS.get(key)
    if doc:
        lines.extend(_wrap_comment(doc))
    # db_url: per-target — value only where safe, else an explanatory comment.
    if key == "db_url":
        val = spec.DB_URL.get(target)
        if val is None:
            note = spec.DB_URL_NOTE.get(target, "set in the target's env file")
            lines.append(f"# GATEWAY_DB_URL — {note}")
        else:
            lines.append(f"GATEWAY_DB_URL={val}")
        return lines
    if key in spec.SECRETS:
        lines.append(f"# {env_name(key)}=   # SECRET — set in deploy/{target}/{secret_file}")
        return lines
    lines.append(f"{env_name(key)}={fmt(effective_value(target, key))}")
    return lines


def render_all() -> dict[str, str]:
    return {t: render_target(t) for t in spec.TARGETS}


def _config_dir() -> Path:
    """Locate deploy/config/ by walking up from this file (repo checkout only)."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        candidate = parent / "deploy" / "config"
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError(
        "deploy/config/ not found — `generate --write/--check` must run in a repo "
        "checkout, not inside the container image."
    )


def target_path(target: str) -> Path:
    return _config_dir() / f"gateway.{target}.env"
