"""init users, api_keys, jobs

Revision ID: 7013f1926723
Revises: 
Create Date: 2026-07-21 09:28:10.165639
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7013f1926723'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_secret_hash'), ['secret_hash'], unique=False)

    op.create_table('jobs',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('svc', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('fc_task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('output_prefix', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_secret_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_account_id'))

    op.drop_table('api_keys')
    op.drop_table('users')
    # ### end Alembic commands ###
