"""drop api_keys (retire API keys)

Revision ID: e051c0b8eb0c
Revises: f2c6bdf643d2
Create Date: 2026-08-03 16:24:34.975848
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e051c0b8eb0c'
down_revision: str | None = 'f2c6bdf643d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_account_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_secret_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.VARCHAR(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(), nullable=False),
    sa.Column('secret_hash', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_secret_hash'), ['secret_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###
