edition: 3.0.0
name: fc3-example
access: default
resources:
  fcDemo:
    component: fc3
    props:
      region: cn-hangzhou
      handler: index.handler
      imagePrewarmStatus: InProgress
      diskSize: 10240
      instanceLifecycleConfig:
        preStop:
          handler: 'true'
          timeout: 3
      runtime: custom-container
      cpu: 4
      instanceConcurrency: 200
      vpcConfig:
        securityGroupId: sg-bp16eiz6pkbsj4suejie
        anytunnelViaENI: false
        vpcId: vpc-bp1y6pbb5wp095bxej4np
        vSwitchIds:
          - vsw-bp1r8dil1l9hl72qx373t
      role: acs:ram::1713785072839647:role/bioresearch-fc
      disableOndemand: false
      nasConfig:
        groupId: 0
        mountPoints:
          - enableTLS: false
            serverAddr: 0620a487b6-gum23.cn-hangzhou.nas.aliyuncs.com:/fc
            mountDir: /data
        userId: 0
      description: ''
      timeout: 36000
      sessionAffinityConfig:
        affinityHeaderFieldName: bioagent-session-id
        disableSessionIdReuse: false
        enableAutoPause: false
        enableAutoResume: null
        sessionConcurrencyPerInstance: 1
        sessionIdleTimeoutInSeconds: 600
        sessionTTLInSeconds: 86400
      internetAccess: true
      ossMountConfig:
        mountPoints:
          - bucketName: bio-gateway
            endpoint: http://oss-cn-hangzhou-internal.aliyuncs.com
            bucketPath: ''
            mountDir: /mnt/oss
            readOnly: false
      resourceGroupId: rg-aek54blnrbv56ry
      instanceIsolationMode: SHARE
      logConfig:
        enableRequestMetrics: true
        enableInstanceMetrics: true
        logBeginRule: DefaultRegex
        project: serverless-cn-hangzhou-19ebd24e-ebe2-5da6-bf89-3c78e2ce4d70
        logstore: default-logs
      functionName: fc_ppiflow
      sessionAffinity: HEADER_FIELD
      gpuConfig:
        gpuMemorySize: 16384
        gpuType: fc.gpu.tesla.1
      customContainerConfig:
        image: harbor.ruosheng.bio/aliyun_fc/ppiflow-server:v0.0.13
        registryConfig:
          certConfig:
            insecure: false
        port: 9000
        healthCheckConfig: {}
      memorySize: 16384
      environmentVariables:
        PPIFLOW_SESSION_HEADER_NAME: bioagent-session-id
      idleTimeout: 300
      triggers:
        - triggerConfig:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
              - PATCH
            authType: anonymous
            disableURLInternet: true
          triggerName: defaultTrigger
          description: ''
          qualifier: LATEST
          triggerType: http
      asyncInvokeConfig:
        asyncTask: true
        maxAsyncEventAgeInSeconds: 86400
        destinationConfig:
          onFailure:
            destination: ''
          onSuccess:
            destination: ''
        maxAsyncRetryAttempts: 3
